services:
  bot:
    build: .
    container_name: hunting_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["python", "main.py"]
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: hunting_bot_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata_hunting_bot:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: hunting_bot_redis
    restart: always
    volumes:
      - redisdata_hunting_bot:/data

volumes:
  pgdata_hunting_bot:
  redisdata_hunting_bot:
