services:
  db:
    image: postgres:15
    container_name: hunting_bot_db
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - pgdata_hunting_bot:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: hunting_bot_redis
    restart: always
    ports:
      - "6379:6379"
    # опционально — сохранение данных
    volumes:
      - redisdata_hunting_bot:/data

volumes:
  pgdata_hunting_bot:
  redisdata_hunting_bot:
